name: Snow Notifier

on:
  schedule:
    - cron: "0 5 * * *"   # 06:00 SE winter (UTC+1)
    - cron: "0 11 * * *"  # 12:00 SE winter (UTC+1)
    - cron: "0 17 * * *"  # 18:00 SE winter (UTC+1)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    #  - name: Restore alert history
    #    uses: actions/cache@v4
    #    with:
    #      path: .last_alert
    #      key: last-alert

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run notifier script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python smhi.py

    #  - name: Save alert history
    #    uses: actions/cache@v4
    #    with:
    #      path: .last_alert
    #      key: last-alert
